### ISSUE TITLE
--region parameter must be complete path

### ISSUE THREAD

**Issue by tdelhomme** [IARCbioinfo/platypus-nf#15]
At the moment, `--region` parameters is passed to platypus as a string containing the complete path of the bed file (if file is provided and not a true region). [see here](https://github.com/IARCbioinfo/platypus-nf/blob/master/platypus.nf#L123).
A correct code would take the file in input and pass this to the command line. But how do we manage when:
  - `--region` is not a file but a region (**chr:start-end**)
  - no `--region` is provided (conditional input?)

**Comment by valleem** [comment]
I got a dirty if statement on my pipeline [here](https://github.com/IARCbioinfo/gatk4-HaplotypeCaller-nf/blob/1993a6d1c5512f0eeec905484956157e812b0138/gatk4-HaplotypeCaller.nf#L62), that creates a variable holding the `-L` argument if needed. I do not know with Platypus, but with GATK it is robust.

**Comment by tdelhomme** [comment]
@valleem actually I also use this "dirty" solution in some pipelines but here the case is slightly different, the variable is not a string but a file that I would like to have in input such as:
```
input:
file bed
```
which is declared like:
```
bed = file(params.bed)
```

but this input should be optional and this is my problem...

**Comment by valleem** [comment]
@tdelhomme 
Like this :
https://gist.github.com/pditommaso/ff13c333f461ca0d9b839d9e3416b376
?

**Comment by tdelhomme** [comment]
Yes it seems!
I am ashamed to do not have googled correctly...
thanks @valleem!

**Comment by mfoll** [comment]
Actually the trick is that nextflow doesn't complain when you declare as an input a file that doesn't exist.

**Comment by tdelhomme** [comment]
:+1:

**Comment by tdelhomme** [comment]
I think a better way is to use the file in the argument (in the gist it is the path that is used, so not very different than the proposition from @valleem), see [my commit](https://github.com/IARCbioinfo/platypus-nf/commit/478f37646949e28c44992afba8aa6eed615ab063).
